## Load libraries
```{r}
library(dnar)
packageVersion('dnar')
library(taxonomizr)
packageVersion('taxonomizr')
library(parallel)
packageVersion('parallel')
```

## Prepare database of NCBI accession numbers and taxonomy IDs
```{r prepareNCBI,cache=TRUE}
sqlFile<-'work/accessionTaxa.sql'
tmp<-tempdir()
#this is a big download
getNamesAndNodes('work')
getAccession2taxid(tmp)
read.nodes2('work/nodes.dmp',sqlFile)
read.names2('work/names.dmp',sqlFile)
read.accession2taxid(list.files(tmp,'accession2taxid.gz$',full.names=TRUE),sqlFile)
file.remove(list.files(tmp,'accession2taxid.gz$',full.names=TRUE))
```

## Assign taxonomy to blast hits
```{r assignTaxa,cache=TRUE}
blastFiles<-list.files('work/swarmPair','\\.blast\\.gz$',full.names=TRUE)

taxas<-mclapply(blastFiles,function(ii,sqlFile,...){
  message('Parsing blast hits in ',ii)
  outFile<-sub('.blast.gz$','_taxa.csv',ii)
  outFile2<-sub('.blast.gz$','_allHits.csv',ii)
  message(' Creating ',outFile)
  message('  Reading blast')
  x<-read.blast(ii)
  x<-x[x$tName!='ref',]
  x$accession<-sapply(strsplit(x$tName,'\\|'),'[[',3)
  message('  Accession to taxonomy')
  x$taxa<-accessionToTaxa(x$accession,sqlFile)
  x$sumScore<-ave(x$bit,paste(x$tName,x$qName,sep='_-_'),FUN=sum)
  x$maxScore<-ave(x$sumScore,x$qName,FUN=max)
  x<-x[x$sumScore>x$maxScore*.98&!is.na(x$taxa),]
  message('  Getting upstream taxonomy')
  taxonomy<-getTaxonomy2(x$taxa,sqlFile)
  taxonomy<-as.data.frame(taxonomy,stringsAsFactors=FALSE)
  message('  Condensing taxonomy')
  taxaAssigns<-condenseTaxa2(taxonomy,x$qName)
  taxaAssigns<-as.data.frame(taxaAssigns,stringsAsFactors=FALSE)
  rownames(taxaAssigns)<-taxaAssigns$id
  taxaAssigns<-taxaAssigns[,colnames(taxaAssigns)!='id']
  taxonomy$qName<-x$qName
  write.csv(taxonomy,outFile2)
  taxaAssigns$best<-apply(taxaAssigns,1,lastNotNa)
  bestScore<-x[x$sumScore==x$maxScore,c('qName','alignLength','percID','sumScore')]
  bestScore<-bestScore[!duplicated(bestScore$qName),]
  rownames(bestScore)<-bestScore$qName
  taxaAssigns<-cbind(taxaAssigns,'bestScore'=bestScore[rownames(taxaAssigns),c('sumScore')])
  write.csv(taxaAssigns,outFile)
  return(c('taxa'=outFile,'allHits'=outFile2))
},sqlFile,mc.cores=2)
```
