library(actuar)
pcr<-read.csv('pcrPos.csv',stringsAsFactors=FALSE)

like<-function(xx,pcr)-sum(dztbinom(pcr$positive,pcr$replicates,xx,log=TRUE))
mle<-optimize(like,interval=0:1,pcr)
mleBonobo<-optimize(like,interval=0:1,pcr[pcr$Host=='P. paniscus',])
mleChimp<-optimize(like,interval=0:1,pcr[pcr$Host=='P. t. schweifurthii',])


pdf('fit.pdf')
hist(pcr$positive[pcr$replicates==8],breaks=0:9-.5,xlab='Number of positive PCRs',main='8 replicate samples',las=1)
ps<-dztbinom(0:8,8,mle$minimum)
preds<-ps*sum(pcr$replicates==8)
segments(0:8-.5,preds,0:8+.5,preds,col='red')
ps<-dztbinom(0:8,8,.5)
preds<-ps*sum(pcr$replicates==8)
segments(0:8-.5,preds,0:8+.5,preds,col='blue')
hist(pcr$positive[pcr$replicates==10],breaks=0:10-.5,xlab='Number of positive PCRs',main='10 replicate samples',ylim=c(0,1.2),las=1)
ps<-dztbinom(0:10,10,mle$minimum)
preds<-ps*sum(pcr$replicates==10)
segments(0:10-.5,preds,0:10+.5,preds,col='red')
ps<-dztbinom(0:10,10,.5)
preds<-ps*sum(pcr$replicates==10)
segments(0:10-.5,preds,0:10+.5,preds,col='blue')
dev.off()
