## Load libraries
```{r}
library(dnar)
packageVersion('dnar')
```

## Load data
```{r}
source('readData.R')
source('../functions.R')
```

## Compare between 3 TL2 sites and 3 non-endemic sites
```{r}
ss<-samples[order(!samples$bonobo,samples$area2,samples$malaria),]

tlGroups<-withAs(s=ss[ss$bonobo&isEnough[ss$Code]&ss$isTL,],tapply(s$Code,s$area2,c))
nonTlGroups<-withAs(s=ss[ss$bonobo&isEnough[ss$Code]&!ss$isTL,],tapply(s$Code,s$area2,c))
nonTlGroups<-nonTlGroups[sapply(nonTlGroups,length)>5]

comparisons<-expand.grid('tl'=names(tlGroups),'nontl'=names(nonTlGroups))

inBonobo<-otuProp[apply(otuProp[,c(unlist(tlGroups),unlist(nonTlGroups))],1,max)>.001,]
ninePsLt<-apply(inBonobo,1,function(xx)apply(comparisons,1,function(select)suppressWarnings(wilcox.test(xx[tlGroups[[select[1]]]],xx[nonTlGroups[[select[2]]]],alternative='less'))$p.value))

ninePsGt<-apply(inBonobo,1,function(xx)apply(comparisons,1,function(select)suppressWarnings(wilcox.test(xx[tlGroups[[select[1]]]],xx[nonTlGroups[[select[2]]]],alternative='greater')$p.value)))
```{r}

```{r}
condensePLt<-p.adjust(apply(ninePsLt,2,fishers,correct=3),'fdr')
summary(condensePLt)
condensePGt<-p.adjust(apply(ninePsGt,2,fishers,correct=3),'fdr')
summary(condensePGt)
```
