## PCoA and t-SNE of microbial abundances

```{r}
#stop on errors
knitr::opts_chunk$set(error=FALSE,tidy=TRUE)
```

### Load libraries
```{r}
library(phyloseq)
packageVersion('phyloseq')
library(Rtsne)
packageVersion('Rtsne')
library(ape)
packageVersion('ape')
library(dnar)
packageVersion('dnar')
```

### Load the data
```{r}
source('loadData.R')
source('../functions.R')
```



### Calculate distance matrices from OTU table
```{r,cache=TRUE}
  selectSamples<-samples[isEnough[samples$Code],]
  subsampledOtus<-apply(otuTab[rownames(otuTab) %in% tree$tip.label,selectSamples$Code],2,rarefyCounts,nRequiredReads)
  phyOtu<-otu_table(subsampledOtus,taxa_are_rows=TRUE)
  qiimeData<-phyloseq(otu_table=phyOtu,phy_tree=tree)
  uniDist<-UniFrac(qiimeData,weighted=FALSE)
  save(uniDist,file='work/uniDist.Rdat')
  phyOtuW<-otu_table(otuProp[rownames(otuTab) %in% tree$tip.label,selectSamples$Code],taxa_are_rows=TRUE)
  qiimeDataW<-phyloseq(otu_table=phyOtuW,phy_tree=tree)
  uniDistW<-UniFrac(qiimeDataW,weighted=TRUE)
  brayDist<-distance(qiimeDataW,'bray')
  brayDistUW<-distance(qiimeData,'bray',binary=TRUE)
  uniPca<-pcoa(uniDist)
  mantels<-list(
    'uniW'=ade4::mantel.rtest(uniDist,uniDistW,nrepet=1e4),
    'brayW'=ade4::mantel.rtest(uniDist,brayDist,nrepet=1e4),
    'brayUW'=ade4::mantel.rtest(uniDist,brayDistUW,nrepet=1e4)
  )
  predictors<-model.matrix(~0+Species+malaria+SIV+area,selectSamples)
  colnames(predictors)<-sub('^Species','',colnames(predictors))
  colnames(predictors)[colnames(predictors)=='malariaTRUE']<-'malariaPos'
```


### Set up plotting parameters
```{r}
colorBrew<-c('#e41a1cBB','#377eb8BB','#4daf4aBB','#984ea3BB','#ff7f00BB','#ffff33BB','#a65628BB','#f781bfBB','#999999BB','#88ddffBB')
nArea<-length(unique(selectSamples$area2))
if(nArea>length(colorBrew))stop('Need to adjust colors for more areas')
areaCols<-colorBrew[1:nArea]
names(areaCols)<-unique(selectSamples$area2)
areaPch<-sapply(names(areaCols),function(x)mostAbundant(selectSamples$chimpBonobo[selectSamples$area2==x]))
malariaCols<-c('#00000022','#000000CC')
mediumMalariaCol<-'#00000077'
malariaCols3<-c('#00000022','#000000CC')
names(malariaCols3)<-names(malariaCols)<-c('Laverania negative','Laverania positive')
speciesPch<-20+1:length(unique(selectSamples$chimpBonobo))
speciesCols<-rainbow.lab(length(unique(selectSamples$chimpBonobo)),start=-2,end=1,alpha=.8,lightMultiple=.8)
names(speciesCols)<-names(speciesPch)<-sort(unique(selectSamples$chimpBonobo))
importance<-uniPca$values$Relative_eig
colnames(uniPca$vectors)<-sprintf('Principal coordinate %d (%d%% of variance)',1:length(importance),round(importance*100))[1:ncol(uniPca$vectors)]
```
### Plot 16s PCoA
```{r bacteriaPCoA}
  axes<-1:2
  #malaria/species
  pos<-my.biplot.pcoa(uniPca,predictors,plot.axes=axes,pch=21,bg=speciesCols[selectSamples$chimpBonobo],col=malariaCols3[selectSamples$malaria+1],cex=2.25,lwd=4,arrowsFilter=Inf,las=1,mgp=c(2.75,.75,0),sameAxis=FALSE,bty='l',type='n')
  points(pos[!selectSamples$malaria,],col=malariaCols3[1],cex=2.25,lwd=4,bg=speciesCols[selectSamples[!selectSamples$malaria,'chimpBonobo']],pch=21)
  points(pos[selectSamples$malaria,],col=malariaCols3[2],cex=2.25,lwd=4,bg=speciesCols[selectSamples[selectSamples$malaria,'chimpBonobo']],pch=21)
  title(main=sprintf('16S rRNA',axes[1],axes[2]))
```

### Plot 16s t-SNE
```{r bacteria_tSNE}
tsne<-Rtsne(uniDist,is_distance=TRUE,verbose=TRUE,perplexity=15,max_iter=5000)
par(mar=c(4,4,1.5,9.5))
plot(tsne$Y,pch=speciesPch[selectSamples$chimpBonobo],bg=areaCols[selectSamples$area2],col=malariaCols[selectSamples$malaria+1],cex=2.2,lwd=2.5,ylab='t-SNE 2',xlab='t-SNE 1',main='',bty='l')
legend(
  par('usr')[2]+.01*diff(par('usr')[1:2]), 
  mean(par('usr')[3:4]),
  c(names(malariaCols),names(areaCols),names(speciesPch)),
  col=c(malariaCols,rep(c(malariaCols[1],mediumMalariaCol),c(length(areaCols),length(speciesPch)))),
  pch=c(rep(21,length(malariaCols)),speciesPch[areaPch],speciesPch),
  pt.bg=c(rep(NA,length(malariaCols)),areaCols,rep(NA,length(speciesPch))),
  inset=.01,pt.lwd=3,pt.cex=2.5,
  xjust=0,xpd=NA,bty='n'
)
```

### Mantel tests for different distance measures
```{r}
mantels
```
